//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongAn.DVC.WebParts.DeNghiView {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DeNghiView {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal literalTitle;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Repeater rptDeNghi;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DeNghiView target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlliteralTitle() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.literalTitle = @__ctrl;
            @__ctrl.ID = "literalTitle";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <tr>
                            <td>46</td>
                            <td>SGTVTLA-00000033</td>
                            <td>22/08/2014</td>
                            <td>
                                Công ty Tin học ABC
                            </td>
                            <td>
                                Cấp giấy phép A
                            </td>
                            <td>
                                <a href=""#"" class=""button attachment just-icon""></a>
                            </td>
                            <td>
                                <a href=""#"" class=""button printer just-icon""></a>
                            </td>
                            <td>
                                <a href=""#"" class=""button view just-icon""></a>
                            </td>
                            <td>
                                <a href=""#"" class=""button edit just-icon""></a>
                            </td>
                            <td>
                                <label><input type=""checkbox""/>Xóa</label>
                            </td>
                        </tr>
                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrptDeNghi() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            this.rptDeNghi = @__ctrl;
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "rptDeNghi";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::LongAn.DVC.WebParts.DeNghiView.DeNghiView @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link rel=\"stylesheet\" href=\"/_layouts/15/LongAn.Form/css/bootstrap.min.css\"/>\n" +
                        "<!--[if lt IE9]>\n<link rel=\"stylesheet\" href=\"/_layouts/15/LongAn.Form/css/boots" +
                        "trap-non-responsive.min.css\"/>\n<![endif]-->\n<link rel=\"stylesheet\" href=\"/_layou" +
                        "ts/15/LongAn.Form/css/jquery-ui.structure.min.css\"/>\n<link rel=\"stylesheet\" href" +
                        "=\"/_layouts/15/LongAn.Form/css/jquery-ui.min.css\"/>\n<link rel=\"stylesheet\" href=" +
                        "\"/_layouts/15/LongAn.Form/css/bootstrap-theme.min.css\"/>\n<link rel=\"stylesheet\" " +
                        "href=\"/_layouts/15/LongAn.Form/css/form.main.css\"/>\n<script src=\"/_layouts/15/Lo" +
                        "ngAn.Form/js/jquery.js\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/jquer" +
                        "y-ui.min.js\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/datepicker-vi.js" +
                        "\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/modernizr.js\"></script>\n<sc" +
                        "ript src=\"/_layouts/15/LongAn.Form/js/detectizr.min.js\"></script>\n<script src=\"/" +
                        "_layouts/15/LongAn.Form/js/scripts.js\"></script>\r\n<div class=\"container1\">\n    <" +
                        "div class=\"row\">\n        <div class=\"col-lg-9 col-md-9 col-sm-9 col-xs-9\">\n     " +
                        "       <div id=\"top-control\">\n                <a href=\"#\" class=\"button large-bu" +
                        "tton home\">Trang chủ</a>\n                <a href=\"#\" class=\"button large-button " +
                        "add-new\">Thêm mới hồ sơ</a>\n                <a href=\"#\" class=\"button large-butt" +
                        "on added\">Hồ sơ đã tiếp nhận</a>\n                <a href=\"#\" class=\"button large" +
                        "-button process\">Hồ sơ đang xử lý</a>\n                <a href=\"#\" class=\"button " +
                        "large-button waiting\">Hồ sơ chờ cấp phép</a>\n                <a href=\"#\" class=\"" +
                        "button large-button done\">Hồ sơ hoàn thành</a>\n                <a href=\"#\" class" +
                        "=\"button large-button stat\">Báo cáo, thống kê</a>\n                <div class=\"cl" +
                        "earfix\"></div>\n            </div>\n            <h2 class=\"page-header\">\n         " +
                        "       "));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlliteralTitle();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            </h2>
            <div class=""the-form"">
                <div class=""row line"">
                    <div class=""col-lg-4 col-md-4 col-sm-4 col-xs-4"">
                        <input type=""text"" name=""s"" id=""s""/>
                    </div>
                    <div class=""col-lg-2 col-md-2 col-sm-2 col-xs-2"">
                        <button class=""button search"">Tìm kiếm (*)</button>
                    </div>
                </div>
                <div class=""row"">
                    <div class=""col-lg-12 col-md-12 col-sm-12 col-xs-12"">
                        <label><input type=""radio"" name=""match""/>Tìm chính xác</label>
                        <label><input type=""radio"" name=""match""/>Tất cả</label>
                        <label><input type=""radio"" name=""match""/>Từ bất kỳ</label>
                    </div>
                </div>
            </div>
            <div class=""pull-right"">
                <a class=""button add-new"" href=""#"">Thêm mới</a>
            </div>
            <div class=""clearfix""></div>

            <table class=""the-table"">
                <tr>
                    <th>Biên nhận</th>
                    <th>Cá nhân tổ chức</th>
                    <th>Đơn vị đăng ký</th>
                    <th>Loại </th>
                    <th>Ngày đăng ký</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                "));
            global::System.Web.UI.WebControls.Repeater @__ctrl2;
            @__ctrl2 = this.@__BuildControlrptDeNghi();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            </table>
            
            <div class=""pag pull-right"">
                <label for=""go-to"">Trang</label>
                <button class=""button begin small""></button>
                <button class=""button prev small""></button>
                <input type=""text"" id=""go-to"" value=""1"" class=""small""/>
                <button class=""button next small""></button>
                <button class=""button end small""></button>
                <div class=""clearfix""></div>
                Kết quả: 1 to 12 of 12
            </div>
            <div class=""clearfix""></div>
        </div>
    </div>
</div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
