//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongAn.DVC.WebParts.DeNghiView {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DeNghiView {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DeNghiView target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::LongAn.DVC.WebParts.DeNghiView.DeNghiView @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link rel=\"stylesheet\" href=\"/_layouts/15/LongAn.Form/css/bootstrap.min.css\"/>\n" +
                        "<!--[if lt IE9]>\n<link rel=\"stylesheet\" href=\"/_layouts/15/LongAn.Form/css/boots" +
                        "trap-non-responsive.min.css\"/>\n<![endif]-->\n<link rel=\"stylesheet\" href=\"/_layou" +
                        "ts/15/LongAn.Form/css/jquery-ui.structure.min.css\"/>\n<link rel=\"stylesheet\" href" +
                        "=\"/_layouts/15/LongAn.Form/css/jquery-ui.min.css\"/>\n<link rel=\"stylesheet\" href=" +
                        "\"/_layouts/15/LongAn.Form/css/bootstrap-theme.min.css\"/>\n<link rel=\"stylesheet\" " +
                        "href=\"/_layouts/15/LongAn.Form/css/form.main.css\"/>\n<script src=\"/_layouts/15/Lo" +
                        "ngAn.Form/js/jquery.js\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/jquer" +
                        "y-ui.min.js\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/datepicker-vi.js" +
                        "\"></script>\n<script src=\"/_layouts/15/LongAn.Form/js/modernizr.js\"></script>\n<sc" +
                        "ript src=\"/_layouts/15/LongAn.Form/js/detectizr.min.js\"></script>\n<script src=\"/" +
                        "_layouts/15/LongAn.Form/js/scripts.js\"></script>\r\n<div class=\"container1\">\n    <" +
                        "div class=\"row\">\n        <div class=\"col-lg-9 col-md-9 col-sm-9 col-xs-9\">\n     " +
                        "       <div id=\"top-control\">\n                <a href=\"#\" class=\"button large-bu" +
                        "tton home\">Trang chủ</a>\n                <a href=\"#\" class=\"button large-button " +
                        "add-new\">Thêm mới hồ sơ</a>\n                <a href=\"#\" class=\"button large-butt" +
                        "on added\">Hồ sơ đã tiếp nhận</a>\n                <a href=\"#\" class=\"button large" +
                        "-button process\">Hồ sơ đang xử lý</a>\n                <a href=\"#\" class=\"button " +
                        "large-button waiting\">Hồ sơ chờ cấp phép</a>\n                <a href=\"#\" class=\"" +
                        "button large-button done\">Hồ sơ hoàn thành</a>\n                <a href=\"#\" class" +
                        "=\"button large-button stat\">Báo cáo, thống kê</a>\n                <div class=\"cl" +
                        "earfix\"></div>\n            </div>\n            <h2 class=\"page-header\">\n         " +
                        "       DANH SÁCH HỒ SƠ ĐÃ TIẾP NHẬN\n            </h2>\n            <div class=\"th" +
                        "e-form\">\n                <div class=\"row line\">\n                    <div class=\"" +
                        "col-lg-4 col-md-4 col-sm-4 col-xs-4\">\n                        <input type=\"text\"" +
                        " name=\"s\" id=\"s\"/>\n                    </div>\n                    <div class=\"co" +
                        "l-lg-2 col-md-2 col-sm-2 col-xs-2\">\n                        <button class=\"butto" +
                        "n search\">Tìm kiếm (*)</button>\n                    </div>\n                    <" +
                        "div class=\"col-lg-2 col-md-2 col-sm-2 col-xs-2\">\n                        <a href" +
                        "=\"#\" class=\"button task\">Hiển thị tất cả</a>\n                    </div>\n        " +
                        "            <div class=\"col-lg-3 col-md-3 col-sm-3 col-xs-3\">\n                  " +
                        "      <a href=\"#\" class=\"button advantage\">Tìm kiếm nâng cao</a>\n               " +
                        "     </div>\n                </div>\n                <div class=\"row\">\n           " +
                        "         <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n                 " +
                        "       <label><input type=\"radio\" name=\"match\"/>Tìm chính xác</label>\n          " +
                        "              <label><input type=\"radio\" name=\"match\"/>Tất cả</label>\n          " +
                        "              <label><input type=\"radio\" name=\"match\"/>Từ bất kỳ</label>\n       " +
                        "             </div>\n                </div>\n            </div>\n            <div c" +
                        "lass=\"pull-right\">\n                <a class=\"button add-new\" href=\"#\">Thêm mới</" +
                        "a>\n            </div>\n            <div class=\"clearfix\"></div>\n            <tabl" +
                        "e class=\"the-table\">\n                <tr>\n                    <th>ID</th>\n      " +
                        "              <th>Biên nhận (*)</th>\n                    <th>Ngày đăng ký</th>\n " +
                        "                   <th>Đơn vị đăng ký</th>\n                    <th>Loại cấp phép" +
                        "</th>\n                    <th style=\"width: 50px;\">Đính kèm</th>\n               " +
                        "     <th></th>\n                    <th></th>\n                    <th></th>\n     " +
                        "               <th><input type=\"checkbox\" id=\"check-all\"/></th>\n                " +
                        "</tr>\n                <tr>\n                    <td>46</td>\n                    <" +
                        "td>SGTVTLA-00000033</td>\n                    <td>22/08/2014</td>\n               " +
                        "     <td>\n                        Công ty Tin học ABC\n                    </td>\n" +
                        "                    <td>\n                        Cấp giấy phép A\n               " +
                        "     </td>\n                    <td>\n                        <a href=\"#\" class=\"b" +
                        "utton attachment just-icon\"></a>\n                    </td>\n                    <" +
                        "td>\n                        <a href=\"#\" class=\"button printer just-icon\"></a>\n  " +
                        "                  </td>\n                    <td>\n                        <a href" +
                        "=\"#\" class=\"button view just-icon\"></a>\n                    </td>\n              " +
                        "      <td>\n                        <a href=\"#\" class=\"button edit just-icon\"></a" +
                        ">\n                    </td>\n                    <td>\n                        <la" +
                        "bel><input type=\"checkbox\"/>Xóa</label>\n                    </td>\n              " +
                        "  </tr>\n                <tr>\n                    <td>46</td>\n                   " +
                        " <td>SGTVTLA-00000033</td>\n                    <td>22/08/2014</td>\n             " +
                        "       <td>\n                        Công ty Tin học ABC\n                    </td" +
                        ">\n                    <td>\n                        Cấp giấy phép A\n             " +
                        "       </td>\n                    <td>\n                        <a href=\"#\" class=" +
                        "\"button attachment just-icon\"></a>\n                    </td>\n                   " +
                        " <td>\n                        <a href=\"#\" class=\"button printer just-icon\"></a>\n" +
                        "                    </td>\n                    <td>\n                        <a hr" +
                        "ef=\"#\" class=\"button view just-icon\"></a>\n                    </td>\n            " +
                        "        <td>\n                        <a href=\"#\" class=\"button edit just-icon\"><" +
                        "/a>\n                    </td>\n                    <td>\n                        <" +
                        "label><input type=\"checkbox\"/>Xóa</label>\n                    </td>\n            " +
                        "    </tr>\n            </table>\n            <a href=\"#\" class=\"button remove dang" +
                        "er inline-block\">Xóa mục đã chọn</a>\n            <div class=\"pag pull-right\">\n  " +
                        "              <label for=\"go-to\">Trang</label>\n                <button class=\"bu" +
                        "tton begin small\"></button>\n                <button class=\"button prev small\"></" +
                        "button>\n                <input type=\"text\" id=\"go-to\" value=\"1\" class=\"small\"/>\n" +
                        "                <button class=\"button next small\"></button>\n                <but" +
                        "ton class=\"button end small\"></button>\n                <div class=\"clearfix\"></d" +
                        "iv>\n                Kết quả: 1 to 12 of 12\n            </div>\n            <div c" +
                        "lass=\"clearfix\"></div>\n            <div class=\"pull-right\" style=\"margin-top: 15" +
                        "px;\">\n                <a href=\"#\" class=\"button excel inline\">Xuất ra file Excel" +
                        "</a>\n                <a href=\"#\" class=\"button word inline\">Xuất ra file Word</a" +
                        ">\n                <div class=\"clearfix\"></div>\n            </div>\n            <d" +
                        "iv class=\"clearfix\"></div>\n        </div>\n    </div>\n</div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
